from collections import OrderedDict

sync_metadata_tree = {
    'noaa-led-state-summaries-2016': OrderedDict([
        # ('alabama', [
        #     ('/metadata/figures/3819', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3817', 'observed-number-of-very-hot-days', '2a'),
        #     ('/metadata/figures/3818', 'observed-number-of-very-warm-nights', '2b'),
        #     ('/metadata/figures/3815', 'observed-annual-precipitation', '2c'),
        #     ('/metadata/figures/4036', 'total-hurricane-events-in-alabama-1900-2013', '2d'),
        #     ('/metadata/figures/3816', 'observed-number-of-extreme-precipitation-events', '3'),
        #     ('/metadata/figures/3820', 'projected-change-in-spring-precipitation', '4'),
        #     ('/metadata/figures/3821', 'past-and-projected-changes-in-global-sea-level', '5')
        # ]),
        # ('alaska', []),
        # ('arizona', [
        #     ('/metadata/figures/3676', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3672', 'observed-number-of-extremely-hot-days', '2a'),
        #     ('/metadata/figures/3670', 'observed-maximum-summer-temperature', '2b'),
        #     ('/metadata/figures/4083', 'observed-minimum-summer-temperature', '2b'),
        #     ('/metadata/figures/3668', 'observed-annual-precipitation', '2c'),
        #     ('/metadata/figures/3673', 'observed-number-of-extreme-precipitation-events', '2d'),
        #     ('/metadata/figures/3674', 'observed-number-of-extremely-warm-nights', '3'),
        #     ('/metadata/figures/3675', 'observed-number-of-very-cold-nights', '4'),
        #     ('/metadata/figures/3671', 'observed-monsoon-season-precipitation', '5'),
        #     ('/metadata/figures/3903', 'arizona-palmer-drought-severity-index', '6'),
        #     ('/metadata/figures/3890', 'lake-mead-water-level-at-hoover-dam', '7'),
        #     ('/metadata/figures/3677', 'projected-change-in-spring-precipitation', '8')
        # ]),
        # ('arkansas', [
        #     ('/metadata/figures/3954', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3840', 'observed-number-of-extremely-hot-days', '2a'),
        #     ('/metadata/figures/3842', 'observed-number-of-very-cold-nights', '2b'),
        #     ('/metadata/figures/3839', 'observed-annual-precipitation', '2c'),
        #     ('/metadata/figures/3844', 'observed-summer-precipitaton', '2d'),
        #     ('/metadata/figures/3843', 'observed-number-of-very-warm-nights', '3'),
        #     ('/metadata/figures/3845', 'observed-summer-temperature', '4'),
        #     ('/metadata/figures/3841', 'observed-number-of-extreme-precipitation-events', '5'),
        #     ('/metadata/figures/3846', 'projected-change-in-winter-precipitation', '6')
        # ]),
        # ('california', [
        #     ('/metadata/figures/4086', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/4090', 'observed-number-of-extremely-hot-days', '2'),
        #     ('/metadata/figures/4094', 'observed-annual-precipitation', '2b'),
        #     ('/metadata/figures/4089', 'observed-number-of-extreme-precipitation-events', '2c'),
        #     ('/metadata/figures/4095', 'observed-winter-precipitation', '2d'),
        #     ('/metadata/figures/4092', 'observed-number-of-very-warm-nights', '3'),
        #     ('/metadata/figures/4088', 'storage-levels-in-the-shasta-dam-reservoir', '6'),
        #     ('/metadata/figures/4096', 'california-palmer-drought-severity-index', '7'),
        #     ('/metadata/figures/4093', 'projected-change-in-winter-precipitation', '8'),
        #     ('/metadata/figures/4084', 'past-and-projected-changes-in-global-sea-level', '9')
        # ]),
        # ('colorado', [
        #     ('/metadata/figures/3695', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3693', 'observed-number-of-very-hot-days', '2'),
        #     ('/metadata/figures/3697', 'observed-spring-temperature', '3'),
        #     ('/metadata/figures/3698', 'observed-summer-temperature', '3'),
        #     ('/metadata/figures/3691', 'observed-number-of-very-cold-nights', '4'),
        #     ('/metadata/figures/3694', 'observed-number-of-warm-nights', '5a'),
        #     ('/metadata/figures/3689', 'observed-annual-precipitation', '5b'),
        #     ('/metadata/figures/3690', 'observed-fall-precipitation', '5c'),
        #     ('/metadata/figures/3696', 'observed-spring-precipitation', '5c'),
        #     ('/metadata/figures/3692', 'observed-number-of-extreme-precipitation-events', '5d'),
        #     ('/metadata/figures/3893', 'end-of-season-snow-water-equivalent-depth-at-tower', '6'),
        #     ('/metadata/figures/3699', 'projected-change-in-winter-precipitation', '7'),
        #     ('/metadata/figures/3902', 'colorado-palmer-drought-severity-index', '8')
        # ]),
        # ('connecticut', [
        #     ('/metadata/figures/4060', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/4082', 'observed-number-of-very-hot-days', '2a'),
        #     ('/metadata/figures/3848', 'observed-number-of-extreme-precipitation-events', '2b'),
        #     ('/metadata/figures/3847', 'observed-annual-precipitation', '2c'),
        #     ('/metadata/figures/3852', 'observed-summer-precipitaton', '2d'),
        #     ('/metadata/figures/3851', 'observed-number-of-warm-nights', '3'),
        #     ('/metadata/figures/3849', 'observed-number-of-very-cold-nights', '4'),
        #     ('/metadata/figures/3853', 'projected-change-in-spring-precipitation', '5'),
        #     ('/metadata/figures/3876', 'past-and-projected-changes-in-global-sea-level', '7')
        # ]),
        # ('delaware', [
        #     ('/metadata/figures/3761', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3759', 'observed-number-of-very-hot-days', '2a'),
        #     ('/metadata/figures/3757', 'observed-number-of-days-below-freezing', '2b'),
        #     ('/metadata/figures/3756', 'observed-annual-precipitation', '2c'),
        #     ('/metadata/figures/3758', 'observed-number-of-extreme-precipitation-events', '2d'),
        #     ('/metadata/figures/3760', 'observed-number-of-very-warm-nights', '3'),
        #     ('/metadata/figures/3830', 'past-and-projected-changes-in-global-sea-level', '6')
        # ]),
        # ('florida', [
        #     ('/metadata/figures/3767', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3765', 'observed-number-of-very-hot-days', '2a'),
        #     ('/metadata/figures/3951', 'observed-number-of-nights-below-freezing', '2b'),
        #     ('/metadata/figures/3763', 'observed-annual-precipitation', '2c'),
        #     ('/metadata/figures/3766', 'observed-number-of-very-warm-nights', '3'),
        #     ('/metadata/figures/3764', 'observed-number-of-extreme-precipitation-events', '5'),
        #     ('/metadata/figures/3768', 'projected-change-in-summer-precipitation', '6')
        # ]),
        # ('georgia', [
        #     ('/metadata/figures/3774', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3771', 'observed-number-of-extremely-hot-days', '2a'),
        #     ('/metadata/figures/3770', 'observed-number-of-days-below-freezing', '2b'),
        #     ('/metadata/figures/3775', 'observed-summer-precipitaton', '2c'),
        #     ('/metadata/figures/3772', 'observed-number-of-extreme-precipitation-events', '2d'),
        #     ('/metadata/figures/3773', 'observed-number-of-very-warm-nights', '3'),
        #     ('/metadata/figures/3769', 'observed-annual-precipitation', '4'),
        #     ('/metadata/figures/3825', 'past-and-projected-changes-in-global-sea-level', '6')
        # ]),
        # ('hawaii', [
        #     ('/metadata/figures/4108', 'past-and-projected-changes-in-global-sea-level', '9')
        # ]),
        # ('idaho', [
        #     ('/metadata/figures/3645', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3647', 'observed-number-of-very-hot-days', '2'),
        #     ('/metadata/figures/3649', 'observed-number-of-warm-nights', '3'),
        #     ('/metadata/figures/3648', 'observed-number-of-very-cold-nights', '4'),
        #     ('/metadata/figures/3646', 'observed-annual-precipitation', '5'),
        #     ('/metadata/figures/3650', 'observed-number-of-extreme-precipitation-events', '6'),
        #     ('/metadata/figures/3651', 'projected-change-in-spring-precipitation', '7'),
        #     ('/metadata/figures/3906', 'end-of-season-snow-water-equivalent-depth-at-bear-mountain', '8')
        # ]),
        # ('illinois', [
        #     ('/metadata/figures/3663', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3664', 'observed-spring-temperature', '2'),
        #     ('/metadata/figures/3666', 'observed-summer-temperature', '2'),
        #     ('/metadata/figures/3661', 'observed-number-of-very-hot-days', '3a'),
        #     ('/metadata/figures/3662', 'observed-number-of-very-warm-nights', '3b'),
        #     ('/metadata/figures/3660', 'observed-number-of-very-cold-nights', '3c'),
        #     ('/metadata/figures/3832', 'observed-annual-precipitation', '3d'),
        #     ('/metadata/figures/3665', 'observed-summer-precipitaton', '4'),
        #     ('/metadata/figures/3946', 'observed-spring-precipitation', '4'),
        #     ('/metadata/figures/3659', 'observed-number-of-extreme-precipitation-events', '5'),
        #     ('/metadata/figures/3947', 'annual-lake-wide-average-water-levels-for-lake-michigan-huron', '6'),
        #     ('/metadata/figures/3667', 'projected-change-in-spring-precipitation', '8')
        # ]),
        # ('indiana', [
        #     ('/metadata/figures/3683', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3685', 'observed-spring-temperature', '2a'),
        #     ('/metadata/figures/3687', 'observed-summer-temperature', '2a'),
        #     ('/metadata/figures/3681', 'observed-number-of-very-hot-days', '2b'),
        #     ('/metadata/figures/3682', 'observed-number-of-very-warm-nights', '2c'),
        #     ('/metadata/figures/3684', 'observed-spring-precipitaton', '2d'),
        #     ('/metadata/figures/3686', 'observed-summer-precipitaton', '2d'),
        #     ('/metadata/figures/3680', 'observed-number-of-very-cold-nights', '3'),
        #     ('/metadata/figures/3678', 'observed-annual-precipitation', '4'),
        #     ('/metadata/figures/3679', 'observed-number-of-extreme-precipitation-events', '5'),
        #     ('/metadata/figures/3688', 'projected-change-in-spring-precipitation', '7')
        # ]),
        # ('iowa', [
        #     ('/metadata/figures/3700', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3706', 'observed-summer-temperature', '2a'),
        #     ('/metadata/figures/3703', 'observed-number-of-very-hot-days', '2b'),
        #     ('/metadata/figures/3704', 'observed-number-of-very-warm-nights', '2c'),
        #     ('/metadata/figures/3702', 'observed-number-of-very-cold-nights', '2d'),
        #     ('/metadata/figures/3705', 'observed-spring-precipitation', '3'),
        #     ('/metadata/figures/3814', 'observed-summer-precipitaton', '3'),
        #     ('/metadata/figures/3701', 'observed-number-of-extreme-precipitation-events', '5'),
        #     ('/metadata/figures/3708', 'observed-annual-precipitation', '5'),
        #     ('/metadata/figures/3707', 'projected-change-in-spring-precipitation', '6')
        # ]),
        # ('kansas', [
        #     ('/metadata/figures/3601', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3607', 'observed-spring-temperature', '2'),
        #     ('/metadata/figures/3609', 'observed-summer-temperature', '2'),
        #     ('/metadata/figures/3604', 'observed-number-of-very-warm-nights', '3a'),
        #     ('/metadata/figures/3603', 'observed-number-of-extremely-hot-days', '3b'),
        #     ('/metadata/figures/3627', 'observed-annual-precipitation', '3c'),
        #     ('/metadata/figures/3606', 'observed-spring-precipitation', '3d'),
        #     ('/metadata/figures/3608', 'observed-summer-precipitaton', '3d'),
        #     ('/metadata/figures/3602', 'observed-number-of-very-cold-nights', '4'),
        #     ('/metadata/figures/3605', 'observed-number-of-extreme-precipitation-events', '5'),
        #     ('/metadata/figures/3904', 'kansas-palmer-drought-severity-index', '6'),
        #     ('/metadata/figures/3610', 'projected-change-in-winter-precipitation', '7')
        # ]),
        # ('kentucky', [
        #     ('/metadata/figures/3782', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3778', 'observed-number-of-extremely-hot-days', '2a'),
        #     ('/metadata/figures/3784', 'observed-summer-temperature', '2b'),
        #     ('/metadata/figures/3785', 'observed-winter-temperature', '2b'),
        #     ('/metadata/figures/3777', 'observed-annual-precipitation', '2c'),
        #     ('/metadata/figures/3783', 'observed-summer-precipitaton', '2d'),
        #     ('/metadata/figures/3780', 'observed-number-of-very-cold-nights', '3'),
        #     ('/metadata/figures/3781', 'observed-number-of-very-warm-nights', '4'),
        #     ('/metadata/figures/3779', 'observed-number-of-extreme-precipitation-events', '5'),
        #     ('/metadata/figures/3786', 'projected-change-in-spring-precipitation', '6')
        # ]),
        # ('louisiana', [
        #     ('/metadata/figures/3793', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3791', 'observed-number-of-very-hot-days', '2a'),
        #     ('/metadata/figures/3790', 'observed-number-of-days-below-freezing', '2b'),
        #     ('/metadata/figures/3788', 'observed-fall-precipitation', '2c'),
        #     ('/metadata/figures/3794', 'observed-spring-precipitation', '2c'),
        #     ('/metadata/figures/3789', 'observed-number-of-extreme-precipitation-events', '2d'),
        #     ('/metadata/figures/3792', 'observed-number-of-very-warm-nights', '3'),
        #     ('/metadata/figures/3787', 'observed-annual-precipitation', '4'),
        #     ('/metadata/figures/3795', 'projected-change-in-summer-precipitation', '7'),
        #     ('/metadata/figures/3833', 'past-and-projected-changes-in-global-sea-level', '8')
        # ]),
        # ('maine', [
        #     ('/metadata/figures/3961', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3966', 'observed-number-of-hot-days', '2a'),
        #     ('/metadata/figures/3968', 'observed-summer-temperature', '2b'),
        #     ('/metadata/figures/3969', 'observed-winter-temperature', '2b'),
        #     ('/metadata/figures/3964', 'observed-annual-precipitation', '2c'),
        #     ('/metadata/figures/3967', 'observed-number-of-very-cold-nights', '3'),
        #     ('/metadata/figures/3965', 'observed-number-of-extreme-precipitation-events', '4'),
        #     ('/metadata/figures/3962', 'projected-change-in-winter-precipitation', '5'),
        #     ('/metadata/figures/4112', 'past-and-projected-changes-in-global-sea-level', '6')
        # ]),
        # ('maryland', [
        #     ('/metadata/figures/3801', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3799', 'observed-number-of-very-hot-days', '2'),
        #     ('/metadata/figures/3800', 'observed-number-of-very-warm-nights', '2b'),
        #     ('/metadata/figures/3798', 'observed-number-of-very-cold-nights', '2c'),
        #     ('/metadata/figures/3796', 'observed-annual-precipitation', '2d'),
        #     ('/metadata/figures/3797', 'observed-number-of-extreme-precipitation-events', '4'),
        #     ('/metadata/figures/4059', 'past-and-projected-changes-in-global-sea-level', '7')
        # ]),
        # ('massachusetts', [
        #     ('/metadata/figures/4010', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/4051', 'observed-number-of-hot-days', '2'),
        #     ('/metadata/figures/4054', 'observed-number-of-extreme-precipitation-events', '2b'),
        #     ('/metadata/figures/4056', 'observed-annual-precipitation', '2c'),
        #     ('/metadata/figures/4057', 'observed-summer-precipitaton', '2d'),
        #     ('/metadata/figures/4052', 'observed-number-of-warm-nights', '3'),
        #     ('/metadata/figures/4055', 'observed-number-of-very-cold-nights', '4'),
        #     ('/metadata/figures/4011', 'projected-change-in-spring-precipitation', '5'),
        #     ('/metadata/figures/4058', 'past-and-projected-changes-in-global-sea-level', '7')
        # ]),
        # ('michigan', [
        #     ('/metadata/figures/3709', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3712', 'observed-number-of-hot-days', '2a'),
        #     ('/metadata/figures/3713', 'observed-number-of-very-cold-nights', '2b'),
        #     ('/metadata/figures/3714', 'observed-number-of-warm-nights', '2b'),
        #     ('/metadata/figures/3710', 'observed-annual-precipitation', '2d'),
        #     ('/metadata/figures/3711', 'observed-number-of-extreme-precipitation-events', '3'),
        #     ('/metadata/figures/3955', 'annual-lake-wide-average-water-levels-for-lake-michigan-huron', '4'),
        #     ('/metadata/figures/3715', 'projected-change-in-winter-precipitation', '5')
        # ]),
        # ('minnesota', [
        #     ('/metadata/figures/3611', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3613', 'observed-number-of-hot-days', '3'),
        #     ('/metadata/figures/3615', 'observed-number-of-very-warm-nights', '3b'),
        #     ('/metadata/figures/3952', 'observed-number-of-very-cold-days', '3b'),
        #     ('/metadata/figures/3616', 'observed-number-of-extreme-precipitation-events', '3d'),
        #     ('/metadata/figures/3612', 'observed-annual-precipitation', '5'),
        #     ('/metadata/figures/3614', 'observed-annual-precipitation', '5'),
        #     ('/metadata/figures/3617', 'projected-change-in-spring-precipitation', '6')
        # ]),
        # ('mississippi', [
        #     ('/metadata/figures/3948', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3859', 'observed-number-of-very-warm-nights', '2'),
        #     ('/metadata/figures/3861', 'observed-summer-temperature', '3'),
        #     ('/metadata/figures/3857', 'observed-number-of-extreme-precipitation-events', '4'),
        #     ('/metadata/figures/3862', 'projected-change-in-summer-precipitation', '6'),
        #     ('/metadata/figures/3877', 'past-and-projected-changes-in-global-sea-level', '7'),
        #     ('/metadata/figures/3858', 'observed-number-of-days-below-freezing', '7a'),
        #     ('/metadata/figures/3855', 'observed-annual-precipitation', '7c'),
        #     ('/metadata/figures/3860', 'observed-summer-precipitaton', '7d'),
        #     ('/metadata/figures/3856', 'observed-number-of-extremely-hot-days', '8a')
        # ]),
        # ('missouri', [
        #     ('/metadata/figures/3810', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3804', 'observed-maximum-summer-temperature', '2'),
        #     ('/metadata/figures/3805', 'observed-minimum-summer-temperature', '2'),
        #     ('/metadata/figures/3812', 'observed-summer-temperature', '2'),
        #     ('/metadata/figures/3806', 'observed-number-of-extremely-hot-days', '3a'),
        #     ('/metadata/figures/3808', 'observed-number-of-very-cold-nights', '3b'),
        #     ('/metadata/figures/3803', 'observed-annual-precipitation', '3c'),
        #     ('/metadata/figures/3811', 'observed-summer-precipitaton', '3d'),
        #     ('/metadata/figures/3809', 'observed-number-of-very-warm-nights', '4'),
        #     ('/metadata/figures/3807', 'observed-number-of-extreme-precipitation-events', '5'),
        #     ('/metadata/figures/3813', 'projected-change-in-summer-precipitation', '6')
        # ]),
        # ('montana', [
        #     ('/metadata/figures/3723', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3726', 'observed-number-of-very-hot-days', '2a'),
        #     ('/metadata/figures/3727', 'observed-number-of-warm-nights', '2b'),
        #     ('/metadata/figures/3724', 'observed-annual-precipitation', '2c'),
        #     ('/metadata/figures/3731', 'observed-number-of-extreme-precipitation-events', '2d'),
        #     ('/metadata/figures/3725', 'observed-number-of-very-cold-days', '3'),
        #     ('/metadata/figures/3728', 'observed-summer-temperature', '4'),
        #     ('/metadata/figures/3729', 'observed-winter-temperature', '4'),
        #     ('/metadata/figures/3907', 'end-of-season-snow-water-equivalent-depth-at-noisy-basin', '5'),
        #     ('/metadata/figures/3730', 'projected-change-in-spring-precipitation', '6')
        # ]),
        # ('nebraska', [
        #     ('/metadata/figures/4024', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3869', 'observed-summer-temperature', '2'),
        #     ('/metadata/figures/3870', 'observed-winter-temperature', '2'),
        #     ('/metadata/figures/3864', 'observed-number-of-extremely-hot-days', '3a'),
        #     ('/metadata/figures/3867', 'observed-number-or-warm-nights', '3b'),
        #     ('/metadata/figures/3863', 'observed-annual-precipitation', '3c'),
        #     ('/metadata/figures/3868', 'observed-summer-precipitaton', '3d'),
        #     ('/metadata/figures/3866', 'observed-number-of-very-cold-nights', '4'),
        #     ('/metadata/figures/3865', 'observed-number-of-extreme-precipitation-events', '5'),
        #     ('/metadata/figures/3871', 'projected-change-in-winter-precipitation', '6')
        # ]),
        # ('nevada', [
        #     ('/metadata/figures/3949', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3873', 'observed-number-of-very-hot-days', '2'),
        #     ('/metadata/figures/3874', 'observed-number-of-warm-nights', '3'),
        #     ('/metadata/figures/3872', 'observed-annual-precipitation', '4'),
        #     ('/metadata/figures/3892', 'end-of-season-snow-water-equivalent-depth-at-big-creek-summit', '6'),
        #     ('/metadata/figures/3905', 'nevada-palmer-drought-severity-index', '6'),
        #     ('/metadata/figures/3891', 'lake-mead-elevation-at-hoover-dam', '7')
        # ]),
        # ('new-hampshire', [
        #     ('/metadata/figures/4062', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/4066', 'observed-number-of-hot-days', '2'),
        #     ('/metadata/figures/4069', 'observed-number-of-warm-nights', '2b'),
        #     ('/metadata/figures/4064', 'observed-annual-precipitation', '2c'),
        #     ('/metadata/figures/4067', 'observed-summer-precipitaton', '2d'),
        #     ('/metadata/figures/4068', 'observed-number-of-very-cold-nights', '3'),
        #     ('/metadata/figures/4065', 'observed-number-of-extreme-precipitation-events', '4'),
        #     ('/metadata/figures/4063', 'projected-change-in-winter-precipitation', '5'),
        #     ('/metadata/figures/4078', 'past-and-projected-changes-in-global-sea-level', '6')
        # ]),
        # ('new-jersey', [
        #     ('/metadata/figures/3976', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3974', 'observed-number-of-very-hot-days', '2a'),
        #     ('/metadata/figures/3973', 'observed-number-of-very-cold-nights', '2b'),
        #     ('/metadata/figures/3971', 'observed-annual-precipitation', '2c'),
        #     ('/metadata/figures/3977', 'observed-summer-precipitaton', '2d'),
        #     ('/metadata/figures/3975', 'observed-number-of-warm-nights', '3'),
        #     ('/metadata/figures/3972', 'observed-number-of-extreme-precipitation-events', '4'),
        #     ('/metadata/figures/3978', 'projected-change-in-spring-precipitation', '5'),
        #     ('/metadata/figures/3979', 'past-and-projected-changes-in-global-sea-level', '7')
        # ]),
        ('new-mexico', [
            ('/metadata/figures/3620', 'observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3622', 'observed-number-of-extremely-hot-days', '2'),
            ('/metadata/figures/3624', 'observed-number-of-warm-nights', '3'),
            ('/metadata/figures/3628', 'observed-number-of-very-cold-nights', '4a'),
            ('/metadata/figures/3621', 'observed-annual-precipitation', '4b'),
            ('/metadata/figures/3623', 'observed-number-of-extreme-precipitation-events', '4c'),
            ('/metadata/figures/3619', 'observed-monsoon-season-precipitation', '4d'),
            ('/metadata/figures/3618', 'storage-levels-in-the-elephant-butte-reservoir', '5'),
            ('/metadata/figures/3626', 'projected-change-in-spring-precipitation', '6'),
            ('/metadata/figures/3625', 'new-mexico-palmer-drought-severity-index', '7')
        ]),
        # ('new-york', [
        #     ('/metadata/figures/3958', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3885', 'observed-summer-temperature', '2a'),
        #     ('/metadata/figures/3886', 'observed-winter-temperature', '2a'),
        #     ('/metadata/figures/3883', 'observed-number-of-very-hot-days', '2b'),
        #     ('/metadata/figures/3884', 'observed-number-of-warm-nights', '2c'),
        #     ('/metadata/figures/3880', 'observed-annual-precipitation', '2d'),
        #     ('/metadata/figures/3882', 'observed-number-of-very-cold-nights', '3'),
        #     ('/metadata/figures/3881', 'observed-number-of-extreme-precipitation-events', '5'),
        #     ('/metadata/figures/3889', 'past-and-projected-changes-in-global-sea-level', '6'),
        #     ('/metadata/figures/3887', 'projected-change-in-winter-precipitation', '8')
        # ]),
        # ('north-carolina', [
        #     ('/metadata/figures/3752', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3753', 'observed-summer-temperature', '2'),
        #     ('/metadata/figures/3754', 'observed-winter-temperature', '2'),
        #     ('/metadata/figures/3748', 'observed-annual-precipitation', '3b'),
        #     ('/metadata/figures/3749', 'observed-number-of-extreme-precipitation-events', '3d'),
        #     ('/metadata/figures/3750', 'observed-number-of-very-hot-days', '4'),
        #     ('/metadata/figures/3751', 'observed-number-of-very-warm-nights', '4'),
        #     ('/metadata/figures/3826', 'past-and-projected-changes-in-global-sea-level', '6')
        # ]),
        # ('north-dakota', [
        #     ('/metadata/figures/3652', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3654', 'observed-number-of-very-hot-days', '2'),
        #     ('/metadata/figures/3656', 'observed-number-of-warm-nights', '3'),
        #     ('/metadata/figures/3655', 'observed-number-of-very-cold-days', '4'),
        #     ('/metadata/figures/3653', 'observed-annual-precipitation', '5'),
        #     ('/metadata/figures/3657', 'observed-number-of-extreme-precipitation-events', '6'),
        #     ('/metadata/figures/3658', 'projected-change-in-winter-precipitation', '8')
        # ]),
        # ('ohio', [
        #     ('/metadata/figures/3737', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3735', 'observed-number-of-very-hot-days', '2a'),
        #     ('/metadata/figures/3734', 'observed-number-of-very-cold-nights', '2b'),
        #     ('/metadata/figures/3732', 'observed-annual-precipitation', '2c'),
        #     ('/metadata/figures/3738', 'observed-summer-precipitaton', '2d'),
        #     ('/metadata/figures/3739', 'observed-winter-precipitation', '2d'),
        #     ('/metadata/figures/3736', 'observed-number-of-warm-nights', '3'),
        #     ('/metadata/figures/3733', 'observed-number-of-extreme-precipitation-events', '4'),
        #     ('/metadata/figures/3740', 'projected-change-in-spring-precipitation', '5')
        # ]),
        # ('oklahoma', [
        #     ('/metadata/figures/3959', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3900', 'observed-summer-temperature', '2'),
        #     ('/metadata/figures/3895', 'observed-number-of-extremely-hot-days', '3a'),
        #     ('/metadata/figures/3897', 'observed-number-of-extremely-warm-nights', '3b'),
        #     ('/metadata/figures/3894', 'observed-annual-precipitation', '3c'),
        #     ('/metadata/figures/3899', 'observed-summer-precipitaton', '3d'),
        #     ('/metadata/figures/3898', 'observed-number-of-very-cold-nights', '4'),
        #     ('/metadata/figures/3896', 'observed-number-of-extreme-precipitation-events', '5'),
        #     ('/metadata/figures/3928', 'oklahoma-palmer-drought-severity-index', '6'),
        #     ('/metadata/figures/3901', 'projected-change-in-summer-precipitation', '7')
        # ]),
        # ('oregon', [
        #     ('/metadata/figures/3746', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3743', 'observed-number-of-extremely-hot-days', '2'),
        #     ('/metadata/figures/3742', 'observed-number-of-days-below-freezing', '3'),
        #     ('/metadata/figures/3741', 'observed-annual-precipitation', '3c'),
        #     ('/metadata/figures/3745', 'observed-number-of-very-cold-nights', '4'),
        #     ('/metadata/figures/3828', 'observed-number-of-warm-nights', '4b'),
        #     ('/metadata/figures/3744', 'observed-number-of-extreme-precipitation-events', '4d'),
        #     ('/metadata/figures/3837', 'end-of-season-snow-water-equivalent-depth-at-mt-hood', '5'),
        #     ('/metadata/figures/3747', 'projected-change-in-winter-precipitation', '6'),
        #     ('/metadata/figures/3838', 'past-and-projected-changes-in-global-sea-level', '7')
        # ]),
        # ('pennsylvania', [
        #     ('/metadata/figures/3960', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3931', 'observed-number-of-hot-days', '2a'),
        #     ('/metadata/figures/3932', 'observed-number-of-very-cold-nights', '2b'),
        #     ('/metadata/figures/3929', 'observed-annual-precipitation', '2c'),
        #     ('/metadata/figures/3930', 'observed-number-of-extreme-precipitation-events', '2d'),
        #     ('/metadata/figures/3933', 'observed-number-of-warm-nights', '3'),
        #     ('/metadata/figures/3945', 'past-and-projected-changes-in-global-sea-level', '4'),
        #     ('/metadata/figures/3935', 'projected-change-in-winter-precipitation', '6')
        # ]),
        # ('rhode-island', [
        #     ('/metadata/figures/4070', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/4073', 'observed-number-of-hot-days', '2'),
        #     ('/metadata/figures/4075', 'observed-number-of-warm-nights', '3a'),
        #     ('/metadata/figures/4072', 'observed-number-of-extreme-precipitation-events', '3b'),
        #     ('/metadata/figures/4079', 'observed-annual-precipitation', '3c'),
        #     ('/metadata/figures/4080', 'observed-summer-precipitaton', '3d'),
        #     ('/metadata/figures/4074', 'observed-number-of-very-cold-nights', '4'),
        #     ('/metadata/figures/4076', 'past-and-projected-changes-in-global-sea-level', '7'),
        # ]),
        # ('south-carolina', [
        #     ('/metadata/figures/4027', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/4032', 'observed-number-of-extremely-hot-days', '2a'),
        #     ('/metadata/figures/4030', 'observed-annual-precipitation', '2c'),
        #     ('/metadata/figures/4033', 'observed-number-of-extreme-precipitation-events', '2d'),
        #     ('/metadata/figures/4034', 'observed-number-of-very-warm-nights', '3'),
        #     ('/metadata/figures/4037', 'past-and-projected-changes-in-global-sea-level', '4'),
        #     ('/metadata/figures/4031', 'observed-number-of-days-below-freezing', '4a')
        # ]),
        # ('south-dakota', [
        #     ('/metadata/figures/4013', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/4022', 'observed-summer-temperature', '2'),
        #     ('/metadata/figures/4023', 'observed-winter-temperature', '2'),
        #     ('/metadata/figures/4017', 'observed-number-of-extremely-hot-days', '3a'),
        #     ('/metadata/figures/4020', 'observed-number-or-warm-nights', '3b'),
        #     ('/metadata/figures/4016', 'observed-annual-precipitation', '3c'),
        #     ('/metadata/figures/4021', 'observed-summer-precipitaton', '3d'),
        #     ('/metadata/figures/4019', 'observed-number-of-very-cold-days', '4'),
        #     ('/metadata/figures/4018', 'observed-number-of-extreme-precipitation-events', '5'),
        #     ('/metadata/figures/4015', 'annual-snowfall-totals-at-menno', '6'),
        #     ('/metadata/figures/4014', 'projected-change-in-winter-precipitation', '7')
        # ]),
        # ('tennessee', [
        #     ('/metadata/figures/3638', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3640', 'observed-number-of-extremely-hot-days', '2'),
        #     ('/metadata/figures/3641', 'observed-number-of-very-warm-nights', '3'),
        #     ('/metadata/figures/3639', 'observed-annual-precipitation', '4'),
        #     ('/metadata/figures/3642', 'observed-number-of-extreme-precipitation-events', '5'),
        #     ('/metadata/figures/3643', 'observed-summer-precipitaton', '6'),
        #     ('/metadata/figures/3644', 'projected-change-in-spring-precipitation', '7')
        # ]),
        # ('texas', [
        #     ('/metadata/figures/4039', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/4045', 'observed-number-of-extremely-hot-days', '2'),
        #     ('/metadata/figures/4048', 'observed-number-of-very-warm-nights', '3'),
        #     ('/metadata/figures/4047', 'observed-number-of-days-below-freezing', '4a'),
        #     ('/metadata/figures/4044', 'observed-annual-precipitation', '4b'),
        #     ('/metadata/figures/4046', 'observed-number-of-extreme-precipitation-events', '4c'),
        #     ('/metadata/figures/4043', 'texas-palmer-drought-severity-index', '6'),
        #     ('/metadata/figures/4042', 'past-and-projected-changes-in-global-sea-level', '9')
        # ]),
        # ('utah', [
        #     ('/metadata/figures/3716', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3718', 'observed-number-of-extremely-hot-days', '2'),
        #     ('/metadata/figures/3721', 'observed-number-of-very-warm-nights', '3'),
        #     ('/metadata/figures/3720', 'observed-number-of-very-cold-nights', '4a'),
        #     ('/metadata/figures/3717', 'observed-annual-precipitation', '4b'),
        #     ('/metadata/figures/3719', 'observed-number-of-extreme-precipitation-events', '4d'),
        #     ('/metadata/figures/3908', 'end-of-season-snow-water-equivalent-depth-at-ben-lomond-peak', '4d'),
        #     ('/metadata/figures/3909', 'utah-palmer-drought-severity-index', '5'),
        #     ('/metadata/figures/3927', 'water-levels-in-the-great-salt-lake-at-saltair-boat-harbor', '6'),
        #     ('/metadata/figures/3722', 'projected-change-in-winter-precipitation', '7')
        # ]),
        # ('vermont', [
        #     ('/metadata/figures/3629', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3632', 'observed-number-of-hot-days', '2a'),
        #     ('/metadata/figures/3634', 'observed-number-of-very-cold-nights', '2b'),
        #     ('/metadata/figures/3630', 'observed-summer-temperature', '2c'),
        #     ('/metadata/figures/3631', 'observed-winter-temperature', '2c'),
        #     ('/metadata/figures/3635', 'observed-number-of-extreme-precipitation-events', '2d'),
        #     ('/metadata/figures/3633', 'observed-number-of-warm-nights', '3'),
        #     ('/metadata/figures/3636', 'observed-annual-precipitation', '5'),
        #     ('/metadata/figures/3637', 'projected-change-in-winter-precipitation', '6')
        # ]),
        # ('virginia', [
        #     ('/metadata/figures/3980', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3985', 'observed-number-of-very-hot-days', '2a'),
        #     ('/metadata/figures/3986', 'observed-number-of-very-warm-nights', '2b'),
        #     ('/metadata/figures/3982', 'observed-annual-precipitation', '2c'),
        #     ('/metadata/figures/3987', 'observed-summer-precipitaton', '2d'),
        #     ('/metadata/figures/3984', 'observed-number-of-very-cold-nights', '3'),
        #     ('/metadata/figures/3988', 'observed-summer-temperature', '4'),
        #     ('/metadata/figures/3983', 'observed-number-of-extreme-precipitation-events', '5'),
        #     ('/metadata/figures/3989', 'past-and-projected-changes-in-global-sea-level', '7')
        # ]),
        # ('washington', [
        #     ('/metadata/figures/3917', 'end-of-season-water-equivalent-depth-at-paradise', 'None'),
        #     ('/metadata/figures/4025', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3914', 'observed-number-of-very-hot-days', '2'),
        #     ('/metadata/figures/3913', 'observed-number-of-very-cold-nights', '3'),
        #     ('/metadata/figures/3912', 'observed-number-of-nights-below-freezing', '4a'),
        #     ('/metadata/figures/3915', 'observed-number-of-warm-nights', '4b'),
        #     ('/metadata/figures/3910', 'observed-annual-precipitation', '4c'),
        #     ('/metadata/figures/3911', 'observed-number-of-extreme-precipitation-events', '4d'),
        #     ('/metadata/figures/4026', 'past-and-projected-changes-in-global-sea-level', '5'),
        #     ('/metadata/figures/3916', 'projected-change-in-winter-precipitation', '7')
        # ]),
        # ('west-virginia', [
        #     ('/metadata/figures/3991', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3996', 'observed-number-of-very-hot-days', '2'),
        #     ('/metadata/figures/3997', 'observed-number-of-warm-nights', '3'),
        #     ('/metadata/figures/3995', 'observed-number-of-very-cold-nights', '4'),
        #     ('/metadata/figures/3993', 'observed-annual-precipitation', '5'),
        #     ('/metadata/figures/3994', 'observed-number-of-extreme-precipitation-events', '6'),
        # ]),
        # ('wisconsin', [
        #     ('/metadata/figures/3998', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/4007', 'observed-summer-temperature', '2a'),
        #     ('/metadata/figures/4009', 'observed-winter-temperature', '2a'),
        #     ('/metadata/figures/4004', 'observed-number-of-very-hot-days', '2b'),
        #     ('/metadata/figures/4005', 'observed-number-of-warm-nights', '2c'),
        #     ('/metadata/figures/4006', 'observed-summer-precipitaton', '2d'),
        #     ('/metadata/figures/4008', 'observed-winter-precipitation', '2d'),
        #     ('/metadata/figures/4003', 'observed-number-of-very-cold-days', '3'),
        #     ('/metadata/figures/4000', 'ice-cover-on-lake-mendota', '4'),
        #     ('/metadata/figures/4001', 'observed-annual-precipitation', '5'),
        #     ('/metadata/figures/4002', 'observed-number-of-extreme-precipitation-events', '6'),
        #     ('/metadata/figures/3956', 'annual-lake-wide-average-water-levels-for-lake-michigan-huron', '7'),
        #     ('/metadata/figures/3999', 'projected-change-in-spring-precipitation', '8'),
        # ]),
        # ('wyoming', [
        #     ('/metadata/figures/3957', 'observed-and-projected-temperature-change', '1'),
        #     ('/metadata/figures/3939', 'observed-number-of-very-hot-days', '2'),
        #     ('/metadata/figures/3940', 'observed-number-of-warm-nights', '3'),
        #     ('/metadata/figures/3938', 'observed-number-of-very-cold-days', '3'),
        #     ('/metadata/figures/3941', 'observed-summer-temperature', '4a'),
        #     ('/metadata/figures/3942', 'observed-winter-temperature', '4a'),
        #     ('/metadata/figures/3936', 'observed-annual-precipitation', '4c'),
        #     ('/metadata/figures/3937', 'observed-number-of-extreme-precipitation-events', '4d'),
        #     ('/metadata/figures/3926', 'end-of-season-snow-water-equivalent-depth-at-lewis-lake-divide', '5'),
        #     ('/metadata/figures/3925', 'projected-change-in-spring-precipitation', '6')
        # ])
    ])
}
