from collections import OrderedDict

sync_metadata_tree = {
    'noaa-led-state-summaries-2017': OrderedDict([
        ('alabama', [
            ('/metadata/figures/3819', 'al-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3817', 'al-observed-number-of-very-hot-days', '2a'),
            ('/metadata/figures/3818', 'al-observed-number-of-very-warm-nights', '2b'),
            ('/metadata/figures/3815', 'al-observed-annual-precipitation', '2c'),
            ('/metadata/figures/4036', 'al-total-hurricane-events-in-alabama-1900-2013', '2d'),
            ('/metadata/figures/3816', 'al-observed-number-of-extreme-precipitation-events', '3'),
            ('/metadata/figures/3820', 'al-projected-change-in-spring-precipitation', '4'),
            ('/metadata/figures/3821', 'al-past-and-projected-changes-in-global-sea-level', '5')
        ]),
        ('alaska', []),
        ('arizona', [
            ('/metadata/figures/3676', 'az-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3672', 'az-observed-number-of-extremely-hot-days', '2a'),
            ('/metadata/figures/3670', 'az-observed-maximum-summer-temperature', '2b'),
            ('/metadata/figures/4083', 'az-observed-minimum-summer-temperature', '2b'),
            ('/metadata/figures/3668', 'az-observed-annual-precipitation', '2c'),
            ('/metadata/figures/3673', 'az-observed-number-of-extreme-precipitation-events', '2d'),
            ('/metadata/figures/3674', 'az-observed-number-of-extremely-warm-nights', '3'),
            ('/metadata/figures/3675', 'az-observed-number-of-very-cold-nights', '4'),
            ('/metadata/figures/3671', 'az-observed-monsoon-season-precipitation', '5'),
            ('/metadata/figures/3903', 'arizona-palmer-drought-severity-index', '6'),
            ('/metadata/figures/3890', 'az-lake-mead-water-level-at-hoover-dam', '7'),
            ('/metadata/figures/3677', 'az-projected-change-in-spring-precipitation', '8')
        ]),
        ('arkansas', [
            ('/metadata/figures/3954', 'ar-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3840', 'ar-observed-number-of-extremely-hot-days', '2a'),
            ('/metadata/figures/3842', 'ar-observed-number-of-very-cold-nights', '2b'),
            ('/metadata/figures/3839', 'ar-observed-annual-precipitation', '2c'),
            ('/metadata/figures/3844', 'ar-observed-summer-precipitation', '2d'),
            ('/metadata/figures/3843', 'ar-observed-number-of-very-warm-nights', '3'),
            ('/metadata/figures/3845', 'ar-observed-summer-temperature', '4'),
            ('/metadata/figures/3841', 'ar-observed-number-of-extreme-precipitation-events', '5'),
            ('/metadata/figures/3846', 'ar-projected-change-in-winter-precipitation', '6')
        ]),
        ('california', [
            ('/metadata/figures/4086', 'ca-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/4090', 'ca-observed-number-of-extremely-hot-days', '2'),
            ('/metadata/figures/4094', 'ca-observed-annual-precipitation', '2b'),
            ('/metadata/figures/4089', 'ca-observed-number-of-extreme-precipitation-events', '2c'),
            ('/metadata/figures/4095', 'ca-observed-winter-precipitation', '2d'),
            ('/metadata/figures/4092', 'ca-observed-number-of-very-warm-nights', '3'),
            ('/metadata/figures/4088', 'ca-storage-levels-in-the-shasta-dam-reservoir', '6'),
            ('/metadata/figures/4096', 'california-palmer-drought-severity-index', '7'),
            ('/metadata/figures/4093', 'ca-projected-change-in-winter-precipitation', '8'),
            ('/metadata/figures/4084', 'ca-past-and-projected-changes-in-global-sea-level', '9')
        ]),
        ('colorado', [
            ('/metadata/figures/3695', 'co-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3697', 'co-observed-spring-temperature', '2a'),
            ('/metadata/figures/3698', 'co-observed-summer-temperature', '2b'),
            ('/metadata/figures/3693', 'co-observed-number-of-very-hot-days', '3'),
            ('/metadata/figures/3691', 'co-observed-number-of-very-cold-nights', '4'),
            ('/metadata/figures/3694', 'co-observed-number-of-warm-nights', '5a'),
            ('/metadata/figures/3689', 'co-observed-annual-precipitation', '5b'),
            ('/metadata/figures/3690', 'co-observed-fall-precipitation', '5c'),
            ('/metadata/figures/3696', 'co-observed-spring-precipitation', '5c'),
            ('/metadata/figures/3692', 'co-observed-number-of-extreme-precipitation-events', '5d'),
            ('/metadata/figures/3893', 'co-end-of-season-snow-water-equivalent-depth-at-tower', '6'),
            ('/metadata/figures/3699', 'co-projected-change-in-winter-precipitation', '7'),
            ('/metadata/figures/3902', 'colorado-palmer-drought-severity-index', '8')
        ]),
        ('connecticut', [
            ('/metadata/figures/4060', 'ct-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/4082', 'ct-observed-number-of-very-hot-days', '2a'),
            ('/metadata/figures/3848', 'ct-observed-number-of-extreme-precipitation-events', '2b'),
            ('/metadata/figures/3847', 'ct-observed-annual-precipitation', '2c'),
            ('/metadata/figures/3852', 'ct-observed-summer-precipitation', '2d'),
            ('/metadata/figures/3851', 'ct-observed-number-of-warm-nights', '3'),
            ('/metadata/figures/3849', 'ct-observed-number-of-very-cold-nights', '4'),
            ('/metadata/figures/3853', 'ct-projected-change-in-spring-precipitation', '5'),
            ('/metadata/figures/3876', 'ct-past-and-projected-changes-in-global-sea-level', '7')
        ]),
        ('delaware', [
            ('/metadata/figures/3761', 'de-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3759', 'de-observed-number-of-very-hot-days', '2a'),
            ('/metadata/figures/3757', 'de-observed-number-of-days-below-freezing', '2b'),
            ('/metadata/figures/3756', 'de-observed-annual-precipitation', '2c'),
            ('/metadata/figures/3758', 'de-observed-number-of-extreme-precipitation-events', '2d'),
            ('/metadata/figures/3760', 'de-observed-number-of-very-warm-nights', '3'),
            ('/metadata/figures/3830', 'de-past-and-projected-changes-in-global-sea-level', '6')
        ]),
        ('florida', [
            ('/metadata/figures/3767', 'fl-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3765', 'fl-observed-number-of-very-hot-days', '2a'),
            ('/metadata/figures/3951', 'fl-observed-number-of-nights-below-freezing', '2b'),
            ('/metadata/figures/3763', 'fl-observed-annual-precipitation', '2c'),
            ('/metadata/figures/3766', 'fl-observed-number-of-very-warm-nights', '3'),
            ('/metadata/figures/3764', 'fl-observed-number-of-extreme-precipitation-events', '5'),
            ('/metadata/figures/3768', 'fl-projected-change-in-summer-precipitation', '6')
        ]),
        ('georgia', [
            ('/metadata/figures/3774', 'ga-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3771', 'ga-observed-number-of-extremely-hot-days', '2a'),
            ('/metadata/figures/3770', 'ga-observed-number-of-days-below-freezing', '2b'),
            ('/metadata/figures/3775', 'ga-observed-summer-precipitation', '2c'),
            ('/metadata/figures/3772', 'ga-observed-number-of-extreme-precipitation-events', '2d'),
            ('/metadata/figures/3773', 'ga-observed-number-of-very-warm-nights', '3'),
            ('/metadata/figures/3769', 'ga-observed-annual-precipitation', '4'),
            ('/metadata/figures/3825', 'ga-past-and-projected-changes-in-global-sea-level', '6')
        ]),
        ('hawaii', [
            ('/metadata/figures/4108', 'hi-past-and-projected-changes-in-global-sea-level', '9')
        ]),
        ('idaho', [
            ('/metadata/figures/3645', 'id-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3647', 'id-observed-number-of-very-hot-days', '2'),
            ('/metadata/figures/3649', 'id-observed-number-of-warm-nights', '3'),
            ('/metadata/figures/3648', 'id-observed-number-of-very-cold-nights', '4'),
            ('/metadata/figures/3646', 'id-observed-annual-precipitation', '5'),
            ('/metadata/figures/3650', 'id-observed-number-of-extreme-precipitation-events', '6'),
            ('/metadata/figures/3651', 'id-projected-change-in-spring-precipitation', '7'),
            ('/metadata/figures/3906', 'end-of-season-snow-water-equivalent-depth-at-bear-mountain', '8')
        ]),
        ('illinois', [
            ('/metadata/figures/3663', 'il-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3664', 'il-observed-spring-temperature', '2a'),
            ('/metadata/figures/3666', 'il-observed-summer-temperature', '2b'),
            ('/metadata/figures/3661', 'il-observed-number-of-very-hot-days', '3a'),
            ('/metadata/figures/3662', 'il-observed-number-of-very-warm-nights', '3b'),
            ('/metadata/figures/3660', 'il-observed-number-of-very-cold-nights', '3c'),
            ('/metadata/figures/3832', 'il-observed-annual-precipitation', '3d'),
            ('/metadata/figures/3665', 'il-observed-summer-precipitation', '4'),
            ('/metadata/figures/3946', 'il-observed-spring-precipitation', '4'),
            ('/metadata/figures/3659', 'il-observed-number-of-extreme-precipitation-events', '5'),
            ('/metadata/figures/3947', 'il-annual-lake-wide-average-water-levels-for-lake-michigan-huron', '6'),
            ('/metadata/figures/3667', 'il-projected-change-in-spring-precipitation', '8')
        ]),
        ('indiana', [
            ('/metadata/figures/3683', 'in-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3685', 'in-observed-spring-temperature', '2a'),
            ('/metadata/figures/3687', 'in-observed-summer-temperature', '2a'),
            ('/metadata/figures/3681', 'in-observed-number-of-very-hot-days', '2b'),
            ('/metadata/figures/3682', 'in-observed-number-of-very-warm-nights', '2c'),
            ('/metadata/figures/3684', 'in-observed-spring-precipitation', '2d'),
            ('/metadata/figures/3686', 'in-observed-summer-precipitation', '2d'),
            ('/metadata/figures/3680', 'in-observed-number-of-very-cold-nights', '3'),
            ('/metadata/figures/3678', 'in-observed-annual-precipitation', '4'),
            ('/metadata/figures/3679', 'in-observed-number-of-extreme-precipitation-events', '5'),
            ('/metadata/figures/3688', 'in-projected-change-in-spring-precipitation', '7'),
        ]),
        ('iowa', [
            ('/metadata/figures/3700', 'ia-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3706', 'ia-observed-summer-temperature', '2a'),
            ('/metadata/figures/3703', 'ia-observed-number-of-very-hot-days', '2b'),
            ('/metadata/figures/3704', 'ia-observed-number-of-very-warm-nights', '2c'),
            ('/metadata/figures/3702', 'ia-observed-number-of-very-cold-nights', '2d'),
            ('/metadata/figures/3705', 'ia-observed-spring-precipitation', '3'),
            ('/metadata/figures/3814', 'ia-observed-summer-precipitation', '3'),
            ('/metadata/figures/3701', 'ia-observed-number-of-extreme-precipitation-events', '5'),
            ('/metadata/figures/3708', 'ia-observed-annual-precipitation', '5'),
            ('/metadata/figures/3707', 'ia-projected-change-in-spring-precipitation', '6')
        ]),
        ('kansas', [
            ('/metadata/figures/3601', 'ks-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3607', 'ks-observed-spring-temperature', '2'),
            ('/metadata/figures/3609', 'ks-observed-summer-temperature', '2'),
            ('/metadata/figures/3604', 'ks-observed-number-of-very-warm-nights', '3a'),
            ('/metadata/figures/3603', 'ks-observed-number-of-extremely-hot-days', '3b'),
            ('/metadata/figures/3627', 'ks-observed-annual-precipitation', '3c'),
            ('/metadata/figures/3606', 'ks-observed-spring-precipitation', '3d'),
            ('/metadata/figures/3608', 'ks-observed-summer-precipitation', '3d'),
            ('/metadata/figures/3602', 'ks-observed-number-of-very-cold-nights', '4'),
            ('/metadata/figures/3605', 'ks-observed-number-of-extreme-precipitation-events', '5'),
            ('/metadata/figures/3904', 'kansas-palmer-drought-severity-index', '6'),
            ('/metadata/figures/3610', 'ks-projected-change-in-winter-precipitation', '7')
        ]),
        ('kentucky', [
            ('/metadata/figures/3782', 'ky-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3778', 'ky-observed-number-of-extremely-hot-days', '2a'),
            ('/metadata/figures/3784', 'ky-observed-summer-temperature', '2b'),
            ('/metadata/figures/3785', 'ky-observed-winter-temperature', '2b'),
            ('/metadata/figures/3777', 'ky-observed-annual-precipitation', '2c'),
            ('/metadata/figures/3783', 'ky-observed-summer-precipitation', '2d'),
            ('/metadata/figures/3780', 'ky-observed-number-of-very-cold-nights', '3'),
            ('/metadata/figures/3781', 'ky-observed-number-of-very-warm-nights', '4'),
            ('/metadata/figures/3779', 'ky-observed-number-of-extreme-precipitation-events', '5'),
            ('/metadata/figures/3786', 'ky-projected-change-in-spring-precipitation', '6')
        ]),
        ('louisiana', [
            ('/metadata/figures/3793', 'la-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3791', 'la-observed-number-of-very-hot-days', '2a'),
            ('/metadata/figures/3790', 'la-observed-number-of-days-below-freezing', '2b'),
            ('/metadata/figures/3788', 'la-observed-fall-precipitation', '2c'),
            ('/metadata/figures/3794', 'la-observed-spring-precipitation', '2c'),
            ('/metadata/figures/3789', 'la-observed-number-of-extreme-precipitation-events', '2d'),
            ('/metadata/figures/3792', 'la-observed-number-of-very-warm-nights', '3'),
            ('/metadata/figures/3787', 'la-observed-annual-precipitation', '4'),
            ('/metadata/figures/3795', 'la-projected-change-in-summer-precipitation', '7'),
            ('/metadata/figures/3833', 'la-past-and-projected-changes-in-global-sea-level', '8')
        ]),
        ('maine', [
            ('/metadata/figures/3961', 'me-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3966', 'me-observed-number-of-hot-days', '2a'),
            ('/metadata/figures/3968', 'me-observed-summer-temperature', '2b'),
            ('/metadata/figures/3969', 'me-observed-winter-temperature', '2b'),
            ('/metadata/figures/3964', 'me-observed-annual-precipitation', '2c'),
            ('/metadata/figures/3967', 'me-observed-number-of-very-cold-nights', '3'),
            ('/metadata/figures/3965', 'me-observed-number-of-extreme-precipitation-events', '4'),
            ('/metadata/figures/3962', 'me-projected-change-in-winter-precipitation', '5'),
            ('/metadata/figures/4112', 'me-past-and-projected-changes-in-global-sea-level', '6')
        ]),
        ('maryland', [
            ('/metadata/figures/3801', 'md-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3799', 'md-observed-number-of-very-hot-days', '2'),
            ('/metadata/figures/3800', 'md-observed-number-of-very-warm-nights', '2b'),
            ('/metadata/figures/3798', 'md-observed-number-of-very-cold-nights', '2c'),
            ('/metadata/figures/3796', 'md-observed-annual-precipitation', '2d'),
            ('/metadata/figures/3797', 'md-observed-number-of-extreme-precipitation-events', '4'),
            ('/metadata/figures/4059', 'md-past-and-projected-changes-in-global-sea-level', '7')
        ]),
        ('massachusetts', [
            ('/metadata/figures/4010', 'ma-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/4051', 'ma-observed-number-of-hot-days', '2'),
            ('/metadata/figures/4054', 'ma-observed-number-of-extreme-precipitation-events', '2b'),
            ('/metadata/figures/4056', 'ma-observed-annual-precipitation', '2c'),
            ('/metadata/figures/4057', 'ma-observed-summer-precipitation', '2d'),
            ('/metadata/figures/4052', 'ma-observed-number-of-warm-nights', '3'),
            ('/metadata/figures/4055', 'ma-observed-number-of-very-cold-nights', '4'),
            ('/metadata/figures/4011', 'ma-projected-change-in-spring-precipitation', '5'),
            ('/metadata/figures/4058', 'ma-past-and-projected-changes-in-global-sea-level', '7')
        ]),
        ('michigan', [
            ('/metadata/figures/3709', 'mi-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3712', 'mi-observed-number-of-hot-days', '2a'),
            ('/metadata/figures/3713', 'mi-observed-number-of-very-cold-nights', '2b'),
            ('/metadata/figures/3714', 'mi-observed-number-of-warm-nights', '2b'),
            ('/metadata/figures/3710', 'mi-observed-annual-precipitation', '2d'),
            ('/metadata/figures/3711', 'mi-observed-number-of-extreme-precipitation-events', '3'),
            ('/metadata/figures/3955', 'mi-annual-lake-wide-average-water-levels-for-lake-michigan-huron', '4'),
            ('/metadata/figures/3715', 'mi-projected-change-in-winter-precipitation', '5')
        ]),
        ('minnesota', [
            ('/metadata/figures/3611', 'mn-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3613', 'mn-observed-number-of-hot-days', '3'),
            ('/metadata/figures/3615', 'mn-observed-number-of-very-warm-nights', '3b'),
            ('/metadata/figures/3952', 'mn-observed-number-of-very-cold-days', '3b'),
            ('/metadata/figures/3616', 'mn-observed-number-of-extreme-precipitation-events', '3d'),
            ('/metadata/figures/3612', 'mn-observed-annual-precipitation', '5a'),
            ('/metadata/figures/3614', 'mn-observed-annual-precipitation', '5b'),
            ('/metadata/figures/3617', 'mn-projected-change-in-spring-precipitation', '6'),
        ]),
        ('mississippi', [
            ('/metadata/figures/3948', 'ms-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3859', 'ms-observed-number-of-very-warm-nights', '2'),
            ('/metadata/figures/3861', 'ms-observed-summer-temperature', '3'),
            ('/metadata/figures/3857', 'ms-observed-number-of-extreme-precipitation-events', '4'),
            ('/metadata/figures/3862', 'ms-projected-change-in-summer-precipitation', '6'),
            ('/metadata/figures/3877', 'ms-past-and-projected-changes-in-global-sea-level', '7'),
            ('/metadata/figures/3858', 'ms-observed-number-of-days-below-freezing', '7a'),
            ('/metadata/figures/3855', 'ms-observed-annual-precipitation', '7c'),
            ('/metadata/figures/3860', 'ms-observed-summer-precipitation', '7d'),
            ('/metadata/figures/3856', 'ms-observed-number-of-extremely-hot-days', '8a')
        ]),
        ('missouri', [
            ('/metadata/figures/3810', 'mo-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3804', 'mo-observed-maximum-summer-temperature', '2'),
            ('/metadata/figures/3805', 'mo-observed-minimum-summer-temperature', '2'),
            ('/metadata/figures/3812', 'mo-observed-summer-temperature', '2'),
            ('/metadata/figures/3806', 'mo-observed-number-of-extremely-hot-days', '3a'),
            ('/metadata/figures/3808', 'mo-observed-number-of-very-cold-nights', '3b'),
            ('/metadata/figures/3803', 'mo-observed-annual-precipitation', '3c'),
            ('/metadata/figures/3811', 'mo-observed-summer-precipitation', '3d'),
            ('/metadata/figures/3809', 'mo-observed-number-of-very-warm-nights', '4'),
            ('/metadata/figures/3807', 'mo-observed-number-of-extreme-precipitation-events', '5'),
            ('/metadata/figures/3813', 'mo-projected-change-in-summer-precipitation', '6')
        ]),
        ('montana', [
            ('/metadata/figures/3723', 'mt-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3726', 'mt-observed-number-of-very-hot-days', '2a'),
            ('/metadata/figures/3727', 'mt-observed-number-of-warm-nights', '2b'),
            ('/metadata/figures/3724', 'mt-observed-annual-precipitation', '2c'),
            ('/metadata/figures/3731', 'mt-observed-number-of-extreme-precipitation-events', '2d'),
            ('/metadata/figures/3725', 'mt-observed-number-of-very-cold-days', '3'),
            ('/metadata/figures/3728', 'mt-observed-summer-temperature', '4'),
            ('/metadata/figures/3729', 'mt-observed-winter-temperature', '4'),
            ('/metadata/figures/3907', 'end-of-season-snow-water-equivalent-depth-at-noisy-basin', '5'),
            ('/metadata/figures/3730', 'mt-projected-change-in-spring-precipitation', '6'),
        ]),
        ('nebraska', [
            ('/metadata/figures/4024', 'ne-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3869', 'ne-observed-summer-temperature', '2'),
            ('/metadata/figures/3870', 'ne-observed-winter-temperature', '2'),
            ('/metadata/figures/3864', 'ne-observed-number-of-extremely-hot-days', '3a'),
            ('/metadata/figures/3867', 'ne-observed-number-or-warm-nights', '3b'),
            ('/metadata/figures/3863', 'ne-observed-annual-precipitation', '3c'),
            ('/metadata/figures/3868', 'ne-observed-summer-precipitation', '3d'),
            ('/metadata/figures/3866', 'ne-observed-number-of-very-cold-nights', '4'),
            ('/metadata/figures/3865', 'ne-observed-number-of-extreme-precipitation-events', '5'),
            ('/metadata/figures/3871', 'ne-projected-change-in-winter-precipitation', '6'),
        ]),
        ('nevada', [
            ('/metadata/figures/3949', 'nv-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3873', 'nv-observed-number-of-very-hot-days', '2'),
            ('/metadata/figures/3874', 'nv-observed-number-of-warm-nights', '3'),
            ('/metadata/figures/3872', 'nv-observed-annual-precipitation', '4'),
            ('/metadata/figures/3892', 'nv-end-of-season-snow-water-equivalent-depth-at-big-creek-summit', '6'),
            ('/metadata/figures/3905', 'nevada-palmer-drought-severity-index', '7'),
            ('/metadata/figures/3891', 'nv-lake-mead-elevation-at-hoover-dam', '8')
        ]),
        ('new-hampshire', [
            ('/metadata/figures/4062', 'nh-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/4066', 'nh-observed-number-of-hot-days', '2'),
            ('/metadata/figures/4069', 'nh-observed-number-of-warm-nights', '2b'),
            ('/metadata/figures/4064', 'nh-observed-annual-precipitation', '2c'),
            ('/metadata/figures/4067', 'nh-observed-summer-precipitation', '2d'),
            ('/metadata/figures/4068', 'nh-observed-number-of-very-cold-nights', '3'),
            ('/metadata/figures/4065', 'nh-observed-number-of-extreme-precipitation-events', '4'),
            ('/metadata/figures/4063', 'nh-projected-change-in-winter-precipitation', '5'),
            ('/metadata/figures/4078', 'nh-past-and-projected-changes-in-global-sea-level', '6')
        ]),
        ('new-jersey', [
            ('/metadata/figures/3976', 'nj-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3974', 'nj-observed-number-of-very-hot-days', '2a'),
            ('/metadata/figures/3973', 'nj-observed-number-of-very-cold-nights', '2b'),
            ('/metadata/figures/3971', 'nj-observed-annual-precipitation', '2c'),
            ('/metadata/figures/3977', 'nj-observed-summer-precipitation', '2d'),
            ('/metadata/figures/3975', 'nj-observed-number-of-warm-nights', '3'),
            ('/metadata/figures/3972', 'nj-observed-number-of-extreme-precipitation-events', '4'),
            ('/metadata/figures/3978', 'nj-projected-change-in-spring-precipitation', '5'),
            ('/metadata/figures/3979', 'nj-past-and-projected-changes-in-global-sea-level', '7')
        ]),
        ('new-mexico', [
            ('/metadata/figures/3620', 'nm-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3622', 'nm-observed-number-of-extremely-hot-days', '2'),
            ('/metadata/figures/3624', 'nm-observed-number-of-warm-nights', '3'),
            ('/metadata/figures/3628', 'nm-observed-number-of-very-cold-nights', '4a'),
            ('/metadata/figures/3621', 'nm-observed-annual-precipitation', '4b'),
            ('/metadata/figures/3623', 'nm-observed-number-of-extreme-precipitation-events', '4c'),
            ('/metadata/figures/3619', 'nm-observed-monsoon-season-precipitation', '4d'),
            ('/metadata/figures/3618', 'nm-storage-levels-in-the-elephant-butte-reservoir', '5'),
            ('/metadata/figures/3626', 'nm-projected-change-in-spring-precipitation', '6'),
            ('/metadata/figures/3625', 'new-mexico-palmer-drought-severity-index', '7')
        ]),
        ('new-york', [
            ('/metadata/figures/3958', 'ny-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3885', 'ny-observed-summer-temperature', '2a'),
            ('/metadata/figures/3886', 'ny-observed-winter-temperature', '2a'),
            ('/metadata/figures/3883', 'ny-observed-number-of-very-hot-days', '2b'),
            ('/metadata/figures/3884', 'ny-observed-number-of-warm-nights', '2c'),
            ('/metadata/figures/3880', 'ny-observed-annual-precipitation', '2d'),
            ('/metadata/figures/3882', 'ny-observed-number-of-very-cold-nights', '3'),
            ('/metadata/figures/3881', 'ny-observed-number-of-extreme-precipitation-events', '5'),
            ('/metadata/figures/3889', 'ny-past-and-projected-changes-in-global-sea-level', '6'),
            ('/metadata/figures/3887', 'ny-projected-change-in-winter-precipitation', '8')
        ]),
        ('north-carolina', [
            ('/metadata/figures/3752', 'nc-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3753', 'nc-observed-summer-temperature', '2'),
            ('/metadata/figures/3754', 'nc-observed-winter-temperature', '2'),
            ('/metadata/figures/3748', 'nc-observed-annual-precipitation', '3b'),
            ('/metadata/figures/3749', 'nc-observed-number-of-extreme-precipitation-events', '3d'),
            ('/metadata/figures/3750', 'nc-observed-number-of-very-hot-days', '4'),
            ('/metadata/figures/3751', 'nc-observed-number-of-very-warm-nights', '4'),
            ('/metadata/figures/3826', 'nc-past-and-projected-changes-in-global-sea-level', '6')
        ]),
        ('north-dakota', [
            ('/metadata/figures/3652', 'nd-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3654', 'nd-observed-number-of-very-hot-days', '2'),
            ('/metadata/figures/3656', 'nd-observed-number-of-warm-nights', '3'),
            ('/metadata/figures/3655', 'nd-observed-number-of-very-cold-days', '4'),
            ('/metadata/figures/3653', 'nd-observed-annual-precipitation', '5'),
            ('/metadata/figures/3657', 'nd-observed-number-of-extreme-precipitation-events', '6'),
            ('/metadata/figures/3658', 'nd-projected-change-in-winter-precipitation', '8')
        ]),
        ('ohio', [
            ('/metadata/figures/3737', 'oh-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3735', 'oh-observed-number-of-very-hot-days', '2a'),
            ('/metadata/figures/3734', 'oh-observed-number-of-very-cold-nights', '2b'),
            ('/metadata/figures/3732', 'oh-observed-annual-precipitation', '2c'),
            ('/metadata/figures/3738', 'oh-observed-summer-precipitation', '2d'),
            ('/metadata/figures/3739', 'oh-observed-winter-precipitation', '2d'),
            ('/metadata/figures/3736', 'oh-observed-number-of-warm-nights', '3'),
            ('/metadata/figures/3733', 'oh-observed-number-of-extreme-precipitation-events', '4'),
            ('/metadata/figures/3740', 'oh-projected-change-in-spring-precipitation', '5')
        ]),
        ('oklahoma', [
            ('/metadata/figures/3959', 'ok-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3900', 'ok-observed-summer-temperature', '2'),
            ('/metadata/figures/3895', 'ok-observed-number-of-extremely-hot-days', '3a'),
            ('/metadata/figures/3897', 'ok-observed-number-of-extremely-warm-nights', '3b'),
            ('/metadata/figures/3894', 'ok-observed-annual-precipitation', '3c'),
            ('/metadata/figures/3899', 'ok-observed-summer-precipitation', '3d'),
            ('/metadata/figures/3898', 'ok-observed-number-of-very-cold-nights', '4'),
            ('/metadata/figures/3896', 'ok-observed-number-of-extreme-precipitation-events', '5'),
            ('/metadata/figures/3928', 'oklahoma-palmer-drought-severity-index', '6'),
            ('/metadata/figures/3901', 'ok-projected-change-in-summer-precipitation', '7')
        ]),
        ('oregon', [
            ('/metadata/figures/3746', 'or-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3743', 'or-observed-number-of-extremely-hot-days', '2'),
            ('/metadata/figures/3742', 'or-observed-number-of-days-below-freezing', '3'),
            ('/metadata/figures/3741', 'or-observed-annual-precipitation', '3c'),
            ('/metadata/figures/3745', 'or-observed-number-of-very-cold-nights', '4'),
            ('/metadata/figures/3828', 'or-observed-number-of-warm-nights', '4b'),
            ('/metadata/figures/3744', 'or-observed-number-of-extreme-precipitation-events', '4d'),
            ('/metadata/figures/3837', 'end-of-season-snow-water-equivalent-depth-at-mt-hood', '5'),
            ('/metadata/figures/3747', 'or-projected-change-in-winter-precipitation', '6'),
            ('/metadata/figures/3838', 'or-past-and-projected-changes-in-global-sea-level', '7')
        ]),
        ('pennsylvania', [
            ('/metadata/figures/3960', 'pa-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3931', 'pa-observed-number-of-hot-days', '2a'),
            ('/metadata/figures/3932', 'pa-observed-number-of-very-cold-nights', '2b'),
            ('/metadata/figures/3929', 'pa-observed-annual-precipitation', '2c'),
            ('/metadata/figures/3930', 'pa-observed-number-of-extreme-precipitation-events', '2d'),
            ('/metadata/figures/3933', 'pa-observed-number-of-warm-nights', '3'),
            ('/metadata/figures/3945', 'pa-past-and-projected-changes-in-global-sea-level', '4'),
            ('/metadata/figures/3935', 'pa-projected-change-in-winter-precipitation', '6')
        ]),
        ('rhode-island', [
            ('/metadata/figures/4070', 'ri-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/4073', 'ri-observed-number-of-hot-days', '2'),
            ('/metadata/figures/4075', 'ri-observed-number-of-warm-nights', '3a'),
            ('/metadata/figures/4072', 'ri-observed-number-of-extreme-precipitation-events', '3b'),
            ('/metadata/figures/4079', 'ri-observed-annual-precipitation', '3c'),
            ('/metadata/figures/4080', 'ri-observed-summer-precipitation', '3d'),
            ('/metadata/figures/4074', 'ri-observed-number-of-very-cold-nights', '4'),
            ('/metadata/figures/4076', 'ri-past-and-projected-changes-in-global-sea-level', '7')
        ]),
        ('south-carolina', [
            ('/metadata/figures/4027', 'sc-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/4032', 'sc-observed-number-of-extremely-hot-days', '2a'),
            ('/metadata/figures/4030', 'sc-observed-annual-precipitation', '2c'),
            ('/metadata/figures/4033', 'sc-observed-number-of-extreme-precipitation-events', '2d'),
            ('/metadata/figures/4034', 'sc-observed-number-of-very-warm-nights', '3'),
            ('/metadata/figures/4037', 'sc-past-and-projected-changes-in-global-sea-level', '4'),
            ('/metadata/figures/4031', 'sc-observed-number-of-days-below-freezing', '4a')
        ]),
        ('south-dakota', [
            ('/metadata/figures/4013', 'sd-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/4022', 'sd-observed-summer-temperature', '2'),
            ('/metadata/figures/4023', 'sd-observed-winter-temperature', '2'),
            ('/metadata/figures/4017', 'sd-observed-number-of-extremely-hot-days', '3a'),
            ('/metadata/figures/4020', 'sd-observed-number-or-warm-nights', '3b'),
            ('/metadata/figures/4016', 'sd-observed-annual-precipitation', '3c'),
            ('/metadata/figures/4021', 'sd-observed-summer-precipitation', '3d'),
            ('/metadata/figures/4019', 'sd-observed-number-of-very-cold-days', '4'),
            ('/metadata/figures/4018', 'sd-observed-number-of-extreme-precipitation-events', '5'),
            ('/metadata/figures/4015', 'sd-annual-snowfall-totals-at-menno', '6'),
            ('/metadata/figures/4014', 'sd-projected-change-in-winter-precipitation', '7')
        ]),
        ('tennessee', [
            ('/metadata/figures/3638', 'tn-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3640', 'tn-observed-number-of-extremely-hot-days', '2'),
            ('/metadata/figures/3641', 'tn-observed-number-of-very-warm-nights', '3'),
            ('/metadata/figures/3639', 'tn-observed-annual-precipitation', '4'),
            ('/metadata/figures/3642', 'tn-observed-number-of-extreme-precipitation-events', '5'),
            ('/metadata/figures/3643', 'tn-observed-summer-precipitation', '6'),
            ('/metadata/figures/3644', 'tn-projected-change-in-spring-precipitation', '7')
        ]),
        ('texas', [
            ('/metadata/figures/4039', 'tx-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/4045', 'tx-observed-number-of-extremely-hot-days', '2'),
            ('/metadata/figures/4048', 'tx-observed-number-of-very-warm-nights', '3'),
            ('/metadata/figures/4047', 'tx-observed-number-of-days-below-freezing', '4a'),
            ('/metadata/figures/4044', 'tx-observed-annual-precipitation', '4b'),
            ('/metadata/figures/4046', 'tx-observed-number-of-extreme-precipitation-events', '4c'),
            ('/metadata/figures/4043', 'tx-texas-palmer-drought-severity-index', '6'),
            ('/metadata/figures/4042', 'tx-past-and-projected-changes-in-global-sea-level', '9')
        ]),
        ('utah', [
            ('/metadata/figures/3716', 'ut-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3718', 'ut-observed-number-of-extremely-hot-days', '2'),
            ('/metadata/figures/3721', 'ut-observed-number-of-very-warm-nights', '3'),
            ('/metadata/figures/3720', 'ut-observed-number-of-very-cold-nights', '4a'),
            ('/metadata/figures/3717', 'ut-observed-annual-precipitation', '4b'),
            ('/metadata/figures/3719', 'ut-observed-number-of-extreme-precipitation-events', '4d'),
            ('/metadata/figures/3908', 'ut-end-of-season-snow-water-equivalent-depth-at-ben-lomond-peak', '4d'),
            ('/metadata/figures/3909', 'utah-palmer-drought-severity-index', '5'),
            ('/metadata/figures/3927', 'ut-water-levels-in-the-great-salt-lake-at-saltair-boat-harbor', '6'),
            ('/metadata/figures/3722', 'ut-projected-change-in-winter-precipitation', '7'),
        ]),
        ('vermont', [
            ('/metadata/figures/3629', 'vt-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3632', 'vt-observed-number-of-hot-days', '2a'),
            ('/metadata/figures/3634', 'vt-observed-number-of-very-cold-nights', '2b'),
            ('/metadata/figures/3630', 'vt-observed-summer-temperature', '2c'),
            ('/metadata/figures/3631', 'vt-observed-winter-temperature', '2c'),
            ('/metadata/figures/3635', 'vt-observed-number-of-extreme-precipitation-events', '2d'),
            ('/metadata/figures/3633', 'vt-observed-number-of-warm-nights', '3'),
            ('/metadata/figures/3636', 'vt-observed-annual-precipitation', '5'),
            ('/metadata/figures/3637', 'vt-projected-change-in-winter-precipitation', '6')
        ]),
        ('virginia', [
            ('/metadata/figures/3980', 'va-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3985', 'va-observed-number-of-very-hot-days', '2a'),
            ('/metadata/figures/3986', 'va-observed-number-of-very-warm-nights', '2b'),
            ('/metadata/figures/3982', 'va-observed-annual-precipitation', '2c'),
            ('/metadata/figures/3987', 'va-observed-summer-precipitation', '2d'),
            ('/metadata/figures/3984', 'va-observed-number-of-very-cold-nights', '3'),
            ('/metadata/figures/3988', 'va-observed-summer-temperature', '4'),
            ('/metadata/figures/3983', 'va-observed-number-of-extreme-precipitation-events', '5'),
            ('/metadata/figures/3989', 'va-past-and-projected-changes-in-global-sea-level', '7')
        ]),
        ('washington', [
            ('/metadata/figures/3917', 'end-of-season-water-equivalent-depth-at-paradise', 'None'),
            ('/metadata/figures/4025', 'wa-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3914', 'wa-observed-number-of-very-hot-days', '2'),
            ('/metadata/figures/3913', 'wa-observed-number-of-very-cold-nights', '3'),
            ('/metadata/figures/3912', 'wa-observed-number-of-nights-below-freezing', '4a'),
            ('/metadata/figures/3915', 'wa-observed-number-of-warm-nights', '4b'),
            ('/metadata/figures/3910', 'wa-observed-annual-precipitation', '4c'),
            ('/metadata/figures/3911', 'wa-observed-number-of-extreme-precipitation-events', '4d'),
            ('/metadata/figures/4026', 'wa-past-and-projected-changes-in-global-sea-level', '5'),
            ('/metadata/figures/3916', 'wa-projected-change-in-winter-precipitation', '7')
        ]),
        ('west-virginia', [
            ('/metadata/figures/3991', 'wv-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3996', 'wv-observed-number-of-very-hot-days', '2'),
            ('/metadata/figures/3997', 'wv-observed-number-of-warm-nights', '3'),
            ('/metadata/figures/3995', 'wv-observed-number-of-very-cold-nights', '4'),
            ('/metadata/figures/3993', 'wv-observed-annual-precipitation', '5'),
            ('/metadata/figures/3994', 'wv-observed-number-of-extreme-precipitation-events', '6')
        ]),
        ('wisconsin', [
            ('/metadata/figures/3998', 'wi-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/4007', 'wi-observed-summer-temperature', '2a'),
            ('/metadata/figures/4009', 'wi-observed-winter-temperature', '2a'),
            ('/metadata/figures/4004', 'wi-observed-number-of-very-hot-days', '2b'),
            ('/metadata/figures/4005', 'wi-observed-number-of-warm-nights', '2c'),
            ('/metadata/figures/4006', 'wi-observed-summer-precipitation', '2d'),
            ('/metadata/figures/4008', 'wi-observed-winter-precipitation', '2d'),
            ('/metadata/figures/4003', 'wi-observed-number-of-very-cold-days', '3'),
            ('/metadata/figures/4000', 'wi-ice-cover-on-lake-mendota', '4'),
            ('/metadata/figures/4001', 'wi-observed-annual-precipitation', '5'),
            ('/metadata/figures/4002', 'wi-observed-number-of-extreme-precipitation-events', '6'),
            ('/metadata/figures/3956', 'wi-annual-lake-wide-average-water-levels-for-lake-michigan-huron', '7'),
            ('/metadata/figures/3999', 'wi-projected-change-in-spring-precipitation', '8')
        ]),
        ('wyoming', [
            ('/metadata/figures/3957', 'wy-observed-and-projected-temperature-change', '1'),
            ('/metadata/figures/3939', 'wy-observed-number-of-very-hot-days', '2'),
            ('/metadata/figures/3940', 'wy-observed-number-of-warm-nights', '3'),
            ('/metadata/figures/3938', 'wy-observed-number-of-very-cold-days', '3'),
            ('/metadata/figures/3941', 'wy-observed-summer-temperature', '4a'),
            ('/metadata/figures/3942', 'wy-observed-winter-temperature', '4a'),
            ('/metadata/figures/3936', 'wy-observed-annual-precipitation', '4c'),
            ('/metadata/figures/3937', 'wy-observed-number-of-extreme-precipitation-events', '4d'),
            ('/metadata/figures/3926', 'end-of-season-snow-water-equivalent-depth-at-lewis-lake-divide', '5'),
            ('/metadata/figures/3925', 'wy-projected-change-in-spring-precipitation', '6')
        ])
    ])
}
