<?php
/**
 * Created by IntelliJ IDEA.
 * User: abuddenberg
 * Date: 8/22/13
 * Time: 11:58 AM
 * To change this template use File | Settings | File Templates.
 */

/**
 * Implementation of hook_help().
 */
function formsrv_help($path, $arg) {
    $output = '';
    switch ($path) {
        case "admin/help#formsrv":
            $output = '<p>'.  t("Provides RESTful endpoint for serving out Webform submissions") .'</p>';
            break;
    }
    return $output;
}

/**
 * Implementation of hook_menu().
 */
function formsrv_menu() {
//    $items['metadata/figures/all'] = array(
//        'page callback' => 'formsrv_figure_metadata_json',
//        'type' => MENU_CALLBACK,
//        'access arguments' => array('access content'),
//    );

    $items['metadata/figures'] = array(
        'page callback' => 'formsrv_figure_metadata_json',
        'type' => MENU_CALLBACK,
        'access arguments' => array('access content'),
    );

    $items['metadata/list'] = array(
        'page callback' => 'formsrv_figure_list_json',
        'type' => MENU_CALLBACK,
        'access arguments' => array('access content'),
    );

    return $items;
}

/**
 * Renders a list of figure node IDs with a basic descriptions in JSON.
 */
function formsrv_figure_list_json(){
    $q = <<<END
        #Query to give brief listing and description of figures in Drupal
        SELECT
          n.nid,
          n.title,
          ci.field_metadata_t1_value as t1
        FROM {node} n
          JOIN {content_type_chapter_image} ci ON n.nid = ci.nid AND n.vid = ci.vid
        WHERE n.type = 'chapter_image'
END;
    $list = array();

    $result = db_query($q);
    while($row = $result->fetch_assoc()){
        $list[] = array(
            'nid' => $row['nid'],
            'node_title' => $row['title'],
            'figure_name' => json_decode($row['t1'])->{'figure'}->{'graphics_title'},
            'url' => url('metadata/figures/'.$row['nid'])
        );
    }
    drupal_set_header('Content-Type: application/json');
    echo json_encode($list);
}

/**
 * Creates and populates a tree-like data structure of figures and images with their related datasources.
 * If the node ID of the figure from trh
 * Renders this data structure as JSON.
 */
function formsrv_2_figure_metadata_json($image_nid_query = ''){
    $q = <<<END
        SELECT
          n.nid,
          ci.field_metadata_t1_value as t1,
          ci.field_metadata_t2_value as t2,
          ci.field_cr_permission_status_value as copyright,
          f.filepath
        FROM {node} n
          JOIN {content_type_chapter_image} ci ON n.nid = ci.nid AND n.vid = ci.vid
          JOIN {files} f ON f.fid = ci.field_chapter_image_image_fid
        WHERE n.nid = %d;
END;

    $list = array();

    $result = db_query($q, $image_nid_query);
    while($row = $result->fetch_assoc()){
        $list[] = array(
            'nid' => $row['nid'],
            'copyright' => $row['copyright'],
            't1' => json_decode($row['t1']),
            't2' => json_decode($row['t2']),
            'filepath' => $row['filepath']
        );
    }

    drupal_set_header('Content-Type: application/json');
    echo json_encode($list);
}